# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
resources:
  pipelines:
  - pipeline: abc
    source: Y1
    trigger:
      branches:
      - testing-deploy-build

trigger:
  - testing-deploy-build

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
